export const PRELOAD_WARDROBE = {
    hat: [
      { category: 'hat', name: 'Ushanka', warmthRating: 10, weatherProtection: 'windproof', formalities: ['casual'], image: './closet/ushanka.png' },
      { category: 'hat', name: 'Ralph Lauren Navy Cap', warmthRating: 3, weatherProtection: 'windproof', formalities: ['casual', 'business casual'], image: './closet/ralph-lauren-navy-cap.png' },
      { category: 'hat', name: 'Arcteryx Beanie', warmthRating: 9, weatherProtection: 'both', formalities: ['casual'], image: './closet/arcteryx-beanie.png' },
    ],
    top: [
      { category: 'top', name: 'Blank White Tee', warmthRating: 2, weatherProtection: 'none', formalities: ['casual', 'business casual'], image: './closet/blank-white-tee.png' },
      { category: 'top', name: 'Ralph Lauren Striped Long Sleeve', warmthRating: 3, weatherProtection: 'none', formalities: ['business casual'], image: './closet/ralph-lauren-striped-long-sleeve.png' },
      { category: 'top', name: 'Tom Ford Dress Shirt', warmthRating: 6, weatherProtection: 'none', formalities: ['formal'], image: './closet/tom-ford-dress-shirt.png' },
      { category: 'top', name: 'Black Dress Shirt', warmthRating: 3, weatherProtection: 'none', formalities: ['formal'], image: './closet/black-dress-shirt.png' },
      { category: 'top', name: 'Linen Black Dress Shirt', warmthRating: 2, weatherProtection: 'none', formalities: ['business casual', 'formal'], image: './closet/linen-black-dress-shirt.png' },
      { category: 'top', name: 'Oxford Stripe Shirt', warmthRating: 2, weatherProtection: 'none', formalities: ['formal'], image: './closet/oxford-stripe-shirt.png' },
      { category: 'top', name: 'Skims Thermal Long Sleeve', warmthRating: 9, weatherProtection: 'windproof', formalities: ['casual', 'business casual'], image: './closet/skims-thermal-long-sleeve.png' },
      { category: 'top', name: 'Blank Gray Hoodie', warmthRating: 9, weatherProtection: 'windproof', formalities: ['casual'], image: './closet/blank-gray-hoodie.png' },
      { category: 'top', name: 'Ecru Cable Knit', warmthRating: 8, weatherProtection: 'none', formalities: ['casual'], image: './closet/ecru-cable-knit.png' },
      { category: 'top', name: 'Blank Black Tee', warmthRating: 2, weatherProtection: 'none', formalities: ['casual'], image: './closet/blank-black-tee.png' },
    ],
    bottom: [
      { category: 'bottom', name: 'Jil Sander Trousers', warmthRating: 5, weatherProtection: 'none', formalities: ['casual', 'business casual', 'formal'], image: './closet/jil-sander-trousers.png' },
      { category: 'bottom', name: 'Carhartt Brandon Pant', warmthRating: 5, weatherProtection: 'none', formalities: ['casual'], image: './closet/carhartt-brandon-pant.png' },
      { category: 'bottom', name: 'Linen Trousers', warmthRating: 2, weatherProtection: 'none', formalities: ['business casual', 'casual'], image: './closet/linen-trousers.png' },
      { category: 'bottom', name: 'Cotton Brown Trousers', warmthRating: 2, weatherProtection: 'none', formalities: ['casual', 'business casual'], image: './closet/cotton-brown-trousers.png' },
      { category: 'bottom', name: 'TNF Ski Pants', warmthRating: 10, weatherProtection: 'both', formalities: ['casual'], image: './closet/tnf-ski-pants.png' },
      { category: 'bottom', name: 'Linen Stripe Shorts', warmthRating: 1, weatherProtection: 'windproof', formalities: ['casual'], image: './closet/linen-stripe-shorts.png' },
    ],
    outerwear: [
      { category: 'outerwear', name: 'Emperor Armani Suit Jacket', warmthRating: 5, weatherProtection: 'none', formalities: ['business casual', 'formal'], image: './closet/emperor-armani-suit-jacket.png' },
      { category: 'outerwear', name: 'Double Breasted Suit Jacket', warmthRating: 8, weatherProtection: 'none', formalities: ['formal'], image: './closet/double-breasted-suit-jacket.png' },
      { category: 'outerwear', name: 'Black Trench Coat', warmthRating: 9, weatherProtection: 'windproof', formalities: ['business casual', 'formal'], image: './closet/black-trench-coat.png' },
      { category: 'outerwear', name: 'TNF Puffer Jacket', warmthRating: 10, weatherProtection: 'both', formalities: ['business casual', 'casual'], image: './closet/tnf-puffer-jacket.png' },
      { category: 'outerwear', name: 'Arcteryx Beta Hooded Jacket', warmthRating: 10, weatherProtection: 'both', formalities: ['casual'], image: './closet/arcteryx-beta-hooded-jacket.png' },
    ],
    shoes: [
      { category: 'shoes', name: 'Birkenstock Arizona', warmthRating: 1, weatherProtection: 'none', formalities: ['casual'], image: './closet/birkenstock-arizona.png' },
      { category: 'shoes', name: 'Asics Gel Kayano', warmthRating: 5, weatherProtection: 'waterproof', formalities: ['casual'], image: './closet/asics-gel-kayano.png' },
      { category: 'shoes', name: 'Leather Derbies', warmthRating: 5, weatherProtection: 'none', formalities: ['formal'], image: './closet/leather-derbies.png' },
      { category: 'shoes', name: 'Loro Piana Loafers', warmthRating: 2, weatherProtection: 'none', formalities: ['business casual'], image: './closet/loro-piana-loafers.png' },
      { category: 'shoes', name: 'Loro Piana Chelsea Boot', warmthRating: 8, weatherProtection: 'windproof', formalities: ['business casual', 'formal'], image: './closet/loro-piana-chelsea-boot.png' },
      { category: 'shoes', name: 'Loro Piana Padded Suede Boots', warmthRating: 9, weatherProtection: 'both', formalities: ['casual'], image: './closet/loro-piana-padded-suede-boots.png' },
      { category: 'shoes', name: 'Timberland Boots', warmthRating: 9, weatherProtection: 'both', formalities: ['casual'], image: './closet/timberland-boots.png' },
    ],
    accessories: [
      { category: 'accessories', name: 'Diamond Pattern Tie', warmthRating: 1, weatherProtection: 'none', formalities: ['formal'], image: './closet/diamond-pattern-tie.png' },
      { category: 'accessories', name: 'Single Stripe Silk Tie', warmthRating: 1, weatherProtection: 'none', formalities: ['formal'], image: './closet/single-stripe-silk-tie.png' },
      { category: 'accessories', name: 'Acne Studios Scarf', warmthRating: 9, weatherProtection: 'windproof', formalities: ['casual', 'business casual'], image: './closet/acne-studios-scarf.png' },
      { category: 'accessories', name: 'B Sunglasses', warmthRating: 1, weatherProtection: 'windproof', formalities: ['casual'], image: './closet/b-sunglasses.png' },
      { category: 'accessories', name: 'Gucci Sunglasses', warmthRating: 2, weatherProtection: 'none', formalities: ['business casual'], image: './closet/gucci-sunglasses.png' },
      { category: 'accessories', name: 'Cartier Watch', warmthRating: 1, weatherProtection: 'waterproof', formalities: ['casual', 'business casual'], image: './closet/cartier-watch.png' },
    ],
  };